[versions]
desugar_jdk_libs = "2.1.5"
morphe-patcher = "1.0.0"
# Tracking https://github.com/google/smali/issues/100.
smali = "b6365a84f4"
# 8.3.0 causes java verifier error: https://github.com/ReVanced/revanced-patches/issues/2818.
#noinspection GradleDependency
agp = "8.2.2"
annotation = "1.9.1"
gson = "2.13.2"
guava = "33.5.0-jre"
okhttp = "5.3.2"
androidx-preference = "1.2.1"
material = "1.9.0"
sentry = "8.31.0"

[libraries]
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "androidx-preference" }
material = { module = "com.google.android.material:material", version.ref = "material" }
sentry = { module = "io.sentry:sentry-android", version.ref = "sentry" }

#noinspection NewerVersionAvailable
jackson-databind-boost = { module = "com.fasterxml.jackson.core:jackson-databind", version = "2.6.0" }
jraw-boost = { module = "com.github.wchill:JRAW", version = "454a2f9" }
#noinspection NewerVersionAvailable
slf4j-boost = { module = "org.slf4j:slf4j-api", version = "1.7.13" }
#noinspection NewerVersionAvailable
guava-boost = { module = "com.google.guava:guava", version = "19.0" }

[plugins]
android-library = { id = "com.android.library" }

[bundles]
boost = ["jackson-databind-boost", "jraw-boost", "guava-boost", "slf4j-boost"]
